apiVersion: v1
kind: Pod
metadata:
  name: blue-green-app
spec:
  containers:
    - name: blue-app
      image: yoonjeong/blue-app:1.0
      ports: 
        - containerPort: 8080
      env: 
      - name: NODE_NAME
        valueFrom:
          fieldRef:
            fieldPath: spec.nodeName 
      - name: NAMESPACE_NAME
        valueFrom:
          fieldRef:
            fieldPath: metadata.namespace
      - name: POD_IP
        valueFrom:
          fieldRef:
            fieldPath: status.podIP
      resources:
        limits: 
          memory: 64Mi
          cpu: 250m
    - name: green-app
      image: yoonjeong/green-app:1.0
      ports: 
        - containerPort: 8081
      env:
      - name: NODE_NAME
        valueFrom:
          fieldRef:
            fieldPath: spec.nodeName 
      resources:
        limits:
          memory: 64Mi
          cpu: 250m
