apiVersion: v1 #nginx service
kind: Service
metadata:
  name: nginx-service
  namespace: k8s-istio
spec:
  selector:
    app: nginx
  ports:
  - port: 80
    name: http

---
apiVersion: app/v1 #nginx deployment
kind: Deployment
metadata:
  name: nginx
  namespace: k8s-istio
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
      ports:
      - name:  http
        port:  80
        protocol: TCP  

---      
apiVersion: v1 #redis service
kind: Service
metadata:
  name: redis-service
  namespace: k8s-istio
spec:
  selector:
    app: redis
  ports:
  - port: 6379
    name: redis-port

---
apiVersion: app/v1 #redis deployment
kind: Deployment
metadata:
  name: redis
  namespace: k8s-istio
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis
      ports:
      - name:  http
        port:  80
        protocol: TCP  
