FROM python:3.10-alpine
ENV PYTHONBUFFERED = 1
RUN mkdir /app
WORKDIR /app
COPY requirements.txt /app/requirements.txt

RUN pip3 install --no-cache-dir -r /app/requirements.txt
COPY . /app/
CMD python manage.py runserver 0.0.0.0:8000